# === Homebrew ===
eval "$(/opt/homebrew/bin/brew shellenv)"

# === Go 1.24 ===
export GOROOT="/opt/homebrew/opt/go@1.24/libexec"
export GOPATH="$HOME/go"
export PATH="$GOROOT/bin:$GOPATH/bin:$PATH"
export GO111MODULE=on
export GOPROXY="https://goproxy.byted.org|direct"
export GOPRIVATE="gitlab.everphoto.cn,sysrepo.byted.org"
export GONOSUMDB="*.byted.org"
export GONOPROXY="gitlab.everphoto.cn,sysrepo.byted.org"

# === NVM ===
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"

# === Node.js Memory ===
export NODE_OPTIONS="--max-old-space-size=8192"

# === PATH ===
export PATH="$HOME/.local/bin:$PATH"
export PATH="/Users/bytedance/.opencode/bin:$PATH"

# === API Keys ===
# export ANTHROPIC_API_KEY="your-key-here"
# export DOUBAO_API_KEY="your-key-here"

# === Zsh 补全系统 ===
FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
autoload -Uz compinit
compinit -C

# 补全样式：菜单选择 + 大小写不敏感 + 模糊匹配
zstyle ':completion:*' menu select                          # Tab 弹出菜单，方向键选择
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'  # 大小写不敏感
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"     # 补全列表带颜色
zstyle ':completion:*' group-name ''                        # 分组显示
zstyle ':completion:*:descriptions' format '%F{yellow}-- %d --%f'  # 分组标题高亮

# === 历史记录 ===
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY          # 多终端共享历史
setopt HIST_IGNORE_DUPS       # 去重
setopt HIST_IGNORE_SPACE      # 空格开头不记录

# === 便捷选项 ===
setopt AUTO_CD                # 输入目录名直接 cd
setopt CORRECT                # 命令拼写纠正
setopt INTERACTIVE_COMMENTS   # 允许行内注释

# === 键绑定（emacs 模式，和 bash 一致）===
bindkey -e

# === 插件 ===
# 历史命令灰色建议（按 → 接受，按 Ctrl+→ 接受一个单词）
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history completion)    # 先查历史，再查补全
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#4a6e50"  # 暗绿：与终端绿色字体同色系

# 实时语法高亮（正确命令绿色，错误红色）
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# fzf 模糊搜索（Ctrl+R 搜历史，Ctrl+T 搜文件，Alt+C 跳目录）
source <(fzf --zsh)
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border --info=inline"

# === cmux workspace 自动命名 ===
cmux_auto_rename() {
  if [[ -n "$CMUX_SURFACE_ID" ]]; then
    local name
    if git rev-parse --is-inside-work-tree &>/dev/null 2>&1; then
      name="$(basename "$(git rev-parse --show-toplevel)")"
    else
      name="$(basename "$PWD")"
    fi
    cmux workspace-action --action rename --title "$name" 2>/dev/null &!
  fi
}
chpwd_functions+=(cmux_auto_rename)

# NextCode Personal Access Token
# export NEXTCODE_PAT="your-token-here"

# Feishu/Lark MCP credentials (shared with claude-to-im)
# export FEISHU_APP_ID="your-app-id-here"
# export FEISHU_APP_SECRET="your-secret-here"
export PATH=$HOME/.local/bin:$PATH

# Starship prompt
eval "$(starship init zsh)"

# Source local secrets (NEXTCODE_PAT, API tokens, …) — managed by anygen-inventor bootstrap
[ -f "$HOME/.config/.rc.local" ] && . "$HOME/.config/.rc.local"

# >>> anygen onboarding: garyx PATH >>>
# Generated by skills/ag-onboarding/scripts/install-garyx.sh.
case ":${PATH}:" in
  *":$HOME/.garyx/bin:"*) ;;
  *) export PATH="$HOME/.garyx/bin:$PATH" ;;
esac
# <<< anygen onboarding: garyx PATH <<<

# >>> anygen onboarding: nodejs (nodenv) >>>
# Generated by scripts/onboarding/install-node.sh.
# Full nodenv init (functions + completions) — for interactive shells.
# Edit between the markers; the script will replace this block on re-run.
if command -v nodenv >/dev/null 2>&1; then
  eval "$(nodenv init -)"
fi
# <<< anygen onboarding: nodejs (nodenv) <<<
